services:
  - type: web
    name: esg-detect
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: WEB_CONCURRENCY
        value: 1

